# Generated by Django 5.2.4 on 2025-07-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditations', '0002_initial_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meditation',
            name='language',
        ),
        migrations.AddField(
            model_name='meditation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='meditation',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
