# Generated by Django 5.2.4 on 2025-07-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditations', '0003_remove_meditation_language_meditation_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meditation',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='meditations/'),
        ),
    ]
