# Generated by Django 5.2.4 on 2025-07-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('de', 'Deutsch'), ('es', 'Español'), ('pt', 'Português')], default='fr', max_length=10),
        ),
    ]
