# Generated by Django 5.2.4 on 2025-07-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cycleentry',
            old_name='date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='cycleentry',
            name='cycle_length',
            field=models.IntegerField(default=28),
        ),
        migrations.AddField(
            model_name='cycleentry',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cycleentry',
            name='phase',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
