# Generated by Django 5.2.4 on 2025-07-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0003_cycle_delete_cycleentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='cycle_length',
            field=models.IntegerField(default=28, help_text='Durée moyenne du cycle en jours (21-35)'),
        ),
    ]
