# Generated by Django 5.2.4 on 2025-07-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0004_cycle_cycle_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='appetite',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='Appétit (0-10)', null=True),
        ),
        migrations.AddField(
            model_name='cycle',
            name='energy',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='Énergie (0-10)', null=True),
        ),
        migrations.AddField(
            model_name='cycle',
            name='libido',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='Libido (0-10)', null=True),
        ),
        migrations.AddField(
            model_name='cycle',
            name='mood',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='Humeur (0-10)', null=True),
        ),
        migrations.AddField(
            model_name='cycle',
            name='pain',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='Douleur (0-10)', null=True),
        ),
    ]
