# Generated by Django 5.2.4 on 2025-07-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellnesstip',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='wellnesstip',
            unique_together={('type', 'date')},
        ),
    ]
