# Generated by Django 5.2.4 on 2025-07-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0003_wellnesstip_date_alter_wellnesstip_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellnesstip',
            name='benefits',
            field=models.TextField(blank=True, help_text='Bienfaits du conseil'),
        ),
        migrations.AddField(
            model_name='wellnesstip',
            name='duration',
            field=models.CharField(blank=True, help_text='Durée approximative (ex. 10 minutes)', max_length=50),
        ),
        migrations.AddField(
            model_name='wellnesstip',
            name='steps',
            field=models.TextField(blank=True, help_text='Étapes détaillées pour suivre le conseil'),
        ),
    ]
