# Generated by Django 5.2.4 on 2025-07-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horoscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.CharField(choices=[('aries', 'Bélier'), ('taurus', 'Taureau'), ('gemini', 'Gémeaux'), ('cancer', 'Cancer'), ('leo', 'Lion'), ('virgo', 'Vierge'), ('libra', 'Balance'), ('scorpio', 'Scorpion'), ('sagittarius', 'Sagittaire'), ('capricorn', 'Capricorne'), ('aquarius', 'Verseau'), ('pisces', 'Poissons')], max_length=20)),
                ('date', models.DateField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('sign', 'date')},
            },
        ),
    ]
